title: Med.Plan.
group: ISPRA
header: https://common.intranet.isprambiente.it/head.html
footer: https://common.intranet.isprambiente.it/footer.html
subtitle: Programma per la gestione della segreteria medica
email: medico-competente@isprambiente.it
user_data_lib: nil_data
domain: isprambiente.it
cas: https://auth.isprambiente.it/cas/
rubrica: https://rubrica.intranet.isprambiente.it/home/dettagli
tracker: piwik.intranet.isprambiente.it
app:
  url: https://medplan.intranet.isprambiente.it
copyright:
  title: ISPRA | AGP-INF - Settore Sviluppo
  link: https://www.isprambiente.it
bug:
  icon: bug
  title: Segnala un problema nel programma
  link: https://intranet.isprambiente.it/giri/new/problem/programma-segreteria-medica
  confirm: "Per problematiche relative ad appuntamenti o per contattare la segreteria medica, devi scrivere una e-mail a tuaemail@domain.com<br/><br/>Confermi di voler proseguire?"
events:
  maxusers: 10
  start_time: '07:30'
  end_time: '20:00'
  every_minutes: 10
  visit:
    description: "Presentati all'orario indicato presso l'Ambulatorio sito al piano terra di Via V. Brancati, 48 – lato Banca -"
    location: "Via Vitaliano Brancati 48, Roma, Italia"
  analisys:
    description: "Per gli accertamenti sanitari ISPRA è convenzionata con il laboratorio  MARILAB S.r.l. – Via Caffaro n. 137 – Roma,  raggiungibile con Metro B – fermata Garbatella."
    location: "Via Caffaro 137, Roma, Italia"
audits:
  lab:
    - Marilab
history:
  status:
    - created
    - suitable
    - suitable_prescription_temporary
    - suitable_prescription_permanent
    - unsuitable_temporary
    - unsuitable_permanent
    - deleted
    - change_date_next_visit

database:
  development:
    database: medplan_development
    username: postgres
    host: localhost
    sslmode: prefer
  test:
    database: medplan_test
    username: postgres
    host: localhost
    sslmode: prefer
  staging:
    database: medplan_staging
    username: medplan
    host: db.intranet.isprambiente.it
    sslmode: require
  production:
    database: medplan_production
    username: medplan
    host: db.intranet.isprambiente.it
    sslmode: require

api:
  url: https://api.intranet.isprambiente.it/jpers/medplan.json
  user: medplan
  username: medplan

excel:
  password: nil

action_mailer:
  default_url_option:
    host: 'medplan.intranet.isprambiente.it'
    protocol: 'https'
  smtp_settings:
   address: 'smtp.isprambiente.it'
   port: 465
   domain: 'isprambiente.it'
   ssl: true
   username: 'utenzaservizi01@isprambiente.it'
   sender: 'medplan@isprambiente.it'